def get_metric_keys(module_prepared_results, lens_prepared_results):
    """
    Connects prepared results from a module to metric keys generated by Lens

    Parameters
    ----------
    module_prepared_results : DataFrame
        output of CredoModule.prepare_results()
    lens_prepared_results : DataFrame
        output of lens._prepare_results(assessment)
    """
    return module_prepared_results.merge(lens_prepared_results)['metric_key'].tolist()